"""
Reports page — list and view past Markdown reports from docs/reports/.
"""

import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

import streamlit as st

st.set_page_config(page_title="Reports | OSS Risk Agent", layout="wide")

_REPORTS_DIR = _ROOT / "docs" / "reports"


def _load_reports() -> list[Path]:
    """Return report files sorted newest first."""
    if not _REPORTS_DIR.exists():
        return []
    return sorted(_REPORTS_DIR.glob("risk_report_*.md"), reverse=True)


def _friendly_name(path: Path) -> str:
    """Convert filename to a readable label, e.g. risk_report_2026-04-12T19-36-29 -> 2026-04-12 19:36:29."""
    stem = path.stem  # risk_report_2026-04-12T19-36-29
    ts = stem.replace("risk_report_", "")
    return ts.replace("T", " ").replace("-", ":", 2).replace(":", "-", 2)[:19]


# ── Sidebar ───────────────────────────────────────────────────────────────────

with st.sidebar:
    st.title("OSS Risk Agent")
    st.markdown("---")
    st.subheader("Reports")
    reports = _load_reports()
    if not reports:
        st.info("No reports found.")
    else:
        report_labels = [_friendly_name(r) for r in reports]
        selected_idx = st.selectbox(
            "Select report",
            range(len(reports)),
            format_func=lambda i: report_labels[i],
        )

# ── Main ──────────────────────────────────────────────────────────────────────

st.title("Reports")
st.markdown("View past risk reports generated by the agent.")
st.markdown("---")

reports = _load_reports()

if not reports:
    st.warning(
        "No reports found in `docs/reports/`. "
        "Run the agent on the **Run Agent** page to generate one."
    )
    st.stop()

# Report selector (also available in sidebar)
col_select, col_meta = st.columns([3, 2])
with col_select:
    selected_idx = st.selectbox(
        "Report",
        range(len(reports)),
        format_func=lambda i: _friendly_name(reports[i]),
        key="main_selector",
    )

selected_path = reports[selected_idx]
report_text = selected_path.read_text(encoding="utf-8")

with col_meta:
    size_kb = selected_path.stat().st_size / 1024
    st.markdown(f"**File:** `{selected_path.name}`")
    st.markdown(f"**Size:** {size_kb:.1f} KB")

# Download button
st.download_button(
    label="Download report",
    data=report_text,
    file_name=selected_path.name,
    mime="text/markdown",
)

st.markdown("---")

# ── Summary stats from report header ─────────────────────────────────────────

lines = report_text.splitlines()
for line in lines[:6]:
    if line.startswith("**"):
        st.markdown(line)

st.markdown("---")

# ── Full report ───────────────────────────────────────────────────────────────

st.subheader("Full Report")

# Allow toggling between rendered Markdown and raw text
view_mode = st.radio("View as", ["Rendered", "Raw Markdown"], horizontal=True)

if view_mode == "Rendered":
    st.markdown(report_text)
else:
    st.code(report_text, language="markdown")

# ── Report list summary ───────────────────────────────────────────────────────

with st.expander(f"All reports ({len(reports)} total)"):
    for i, path in enumerate(reports):
        size_kb = path.stat().st_size / 1024
        st.markdown(f"- `{path.name}` ({size_kb:.1f} KB)")
